### ISSUE TITLE
NameError for undefined variable even though variable defined in imported file

### ISSUE THREAD

**Issue by jsdalton** [groenewege/vim-less#14]
vim-less raises a NameError when a variable is undefined. However, it ignores the fact that a variable might be defined somewhere else in an imported file.

**Comment by xavierartot** [comment]
Same for me ?

**Comment by WellerQu** [comment]
@jsdalton eh... I have the same problem, Did you resolve it? Thanks

**Comment by dhruvasagar** [comment]
I am unable to reproduce this, closing for now.
