### ISSUE TITLE
error with MAP

### ISSUE THREAD

**Issue by xavierartot** [groenewege/vim-less#37]
Hi,
When I source the .vimrc, I have some error ?
source ~/.vimrc
/Users/xartot/.vimrc:1: command not found: syn
/Users/xartot/.vimrc:4: command not found: filetype
/Users/xartot/.vimrc:6: command not found: filetype
/Users/xartot/.vimrc:8: parse error near `<'

here my config:
 1 syn on
  2 execute pathogen#infect()
  3 set syntax=on
  4 filetype indent plugin on
  5 
  6 filetype on
  7 
  8 nnoremap <Leader>m :w <BAR> !lessc % > %:t:r.css<CR><space>

Thanks

**Comment by dhruvasagar** [comment]
It looks to be that you sourced your vimrc in your shell instead of within vim. None of these errors make sense. I am closing this issue for now since it doesn't make sense and is even lesser related to the less plugin.
