### ISSUE TITLE
Vim74 syntax issues

### ISSUE THREAD

**Issue by bendavis78** [groenewege/vim-less#42]
I believe Vim74 introduced some new syntax definitions, which is causing properties like "padding", "left", and "border" to be interpreted as cssUIAttr and not cssBoxProp. In my color scheme "padding-left" shows up green, but "padding" shows up purple. I'm not sure exactly how to fix it.

**Comment by luin** [comment]
+1 for this issue, looking forward someone can fix it

**Comment by dhruvasagar** [comment]
Hi,

This has been reported earlier, it's more of a feature rather than an issue since the css plugin tries to distinguish certain properties differently. It's outside the scope of vim-less per say since it's coming directly from vim-less. Closing this for now.
