### ISSUE TITLE
LOOKING FOR HELP

### ISSUE THREAD

**Issue by groenewege** [groenewege/vim-less#51]
Hi,

I made this plugin doing some copy / paste when I tried out VIM a while ago.

I no longer use VIM or LESS and I have very little experience doing VIM script.
Unfortunately, I am not qualified to  fix the current problems with this plugin.

I hope someone more skilled can help or take over the repo.

Please contact me if you can help !

- - - 

Gunther Groenewege
info (at) g-design.net
http://www.g-design.net

**Comment by dhruvasagar** [comment]
Hi,

I use both VIM & LESS, am reasonably proficient with viml. I would like to help.

**Comment by groenewege** [comment]
That's great ! 
Thank you.

**Comment by dhruvasagar** [comment]
I have already forked the repo and i'll try to send pull requests for issues, or you could add me to contributors and I could have a look at others' contributions too if you'd like.

**Comment by dhruvasagar** [comment]
:+1:

**Comment by groenewege** [comment]
I have added you as a contributor. (I think)

**Comment by lkraav** [comment]
https://github.com/genoma/vim-less says that LESS support is included in vim-7.4.567 and later. I think `README.md` can be updated and this project retired.

**Comment by dhruvasagar** [comment]
That's nice to hear, i'll confirm that and update the README, thanks for letting me know @lkraav
