### ISSUE TITLE
Before and after install vim-css3-syntax

### ISSUE THREAD

**Issue by linlinlinlin** [groenewege/vim-less#54]
Highlight colors for some attributes seems different after install vim-css3-syntax.

Witch one is better and correct?

Before
![before css3](https://cloud.githubusercontent.com/assets/8558312/9622113/a0355c98-5161-11e5-91aa-02c73cf6e43b.PNG)

After
![after css3](https://cloud.githubusercontent.com/assets/8558312/9622119/a58a89fc-5161-11e5-999c-305dda1a4ba6.PNG)

**Comment by dhruvasagar** [comment]
Does it matter ?

Answer is both are correct and to consistent in their own way. You'll get used to it gradually.

**Comment by linlinlinlin** [comment]
Doesn't matters. Just want to know which one is more reasonable and want to know why font-size/color/padding are different.

**Comment by dhruvasagar** [comment]
My guess would be they are trying to group similar css3 style attributes into similar syntax groups, you'll really have to look at the actual syntax group they belong to, to get a better idea and sense of things.
