### ISSUE TITLE
It doesn't have any color unless I run `:source $MYVIMRC`?

### ISSUE THREAD

**Issue by yifanchen** [groenewege/vim-less#55]
Fresh start Vim, opening any `.less` file. It doesn't have any colors. But if I run  `:so $MYVIMRC`. It will have colors. 

Any idea what's going on?

**Comment by dhruvasagar** [comment]
This is only for `.less` files or with others as well ?

**Comment by cyfyifanchen** [comment]
The problem seems gone after the update. Thanks for your help.

**Comment by cyfyifanchen** [comment]
This issue is back, it happens on `.less` file with both Vim and Neovim.

**Comment by dhruvasagar** [comment]
Hi,

This seems likely something wrong with your setup, nothing to do with vim-less plugin itself. Try removing plugins and see if it makes a difference.
